# Generated by Django 4.2.1 on 2023-06-04 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(default='headline goes here', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 4, 10, 9, 50, 542352)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
