# Generated by Django 4.2.1 on 2023-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_news_headline_news_updated_alter_news_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='updated',
        ),
    ]
